kafka:
  message_max_bytes: 10485760 # 10MB

api:
  logging:
    level: info

retry_worker:
  logging:
    level: info

content_service:
  aggregate:
    blog_fetch_batch_size: 10
    blogs:
      - name: Example Blog
        url: https://example.com
        rss_url: https://example.com/feed
        blog_type: company
