kafka:
  message_max_bytes: 10485760 # 10MB

api:
  logging:
    level: info

retry_worker:
  logging:
    level: info
    
content_service:
  aggregate:
    blog_fetch_batch_size: 10
    blogs:
      - name: 카카오
        url: https://tech.kakao.com/blog
        rss_url: https://tech.kakao.com/feed/
        blog_type: company

      - name: 카카오페이
        url: https://tech.kakaopay.com
        rss_url: https://tech.kakaopay.com/rss
        blog_type: company

      - name: 네이버
        url: https://d2.naver.com/home
        rss_url: https://d2.naver.com/d2.atom
        blog_type: company

      - name: 당근마켓
        url: https://medium.com/daangn
        rss_url: https://medium.com/feed/daangn
        blog_type: company

      - name: 리멤버
        url: https://tech.remember.co.kr
        rss_url: https://tech.remember.co.kr/feed
        blog_type: company

      - name: 여기어때
        url: https://techblog.gccompany.co.kr/
        rss_url: https://techblog.gccompany.co.kr/feed
        blog_type: company

      - name: 무신사
        url: https://medium.com/musinsa-tech
        rss_url: https://medium.com/feed/musinsa-tech
        blog_type: company

      - name: 쏘카
        url: https://tech.socarcorp.kr/
        rss_url: https://tech.socarcorp.kr/feed
        blog_type: company

      - name: NHN클라우드
        url: https://meetup.nhncloud.com/
        rss_url: https://meetup.nhncloud.com/rss
        blog_type: company

      - name: 컬리
        url: https://helloworld.kurly.com/
        rss_url: https://helloworld.kurly.com/feed
        blog_type: company

      - name: 토스
        url: https://toss.tech/
        rss_url: https://toss.tech/rss.xml
        blog_type: company

      - name: 더핑크퐁컴퍼니
        url: https://medium.com/pinkfong
        rss_url: https://medium.com/feed/pinkfong
        blog_type: company

      - name: 라인
        url: https://techblog.lycorp.co.jp/ko
        rss_url: https://techblog.lycorp.co.jp/ko/feed/index.xml
        blog_type: company

      - name: DEVOCEAN
        url: https://devocean.sk.com/tech
        rss_url: https://devocean.sk.com/blog/rss.do
        blog_type: company

      - name: 44BITS
        url: https://44bits.io/ko
        rss_url: https://www.44bits.io/ko/feed/all
        blog_type: creator

      - name: microservices.io
        url: https://microservices.io/
        rss_url: https://microservices.io/feed.xml
        blog_type: creator

      - name: Uber
        url: https://www.uber.com/en-US/blog/engineering/
        rss_url: https://www.uber.com/en-US/blog/engineering/rss/
        blog_type: company

      - name: 인포그랩
        url: https://insight.infograb.net/blog
        rss_url: https://insight.infograb.net/blog/rss.xml
        blog_type: company

      - name: 인프랩
        url: https://tech.inflab.com
        rss_url: https://tech.inflab.com/rss.xml
        blog_type: company