name: CI/CD Deploy on Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64, techletter-prod]
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop existing application and Run new version
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SUMMARY_WORKER_LLM_API_KEY: ${{ secrets.SUMMARY_WORKER_LLM_API_KEY }}
        run: |
          cp config-production.yaml ./config.yaml
          touch .env
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d --build